### ISSUE TITLE
StyleSheet.create() not giving back the same classes for the same object

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/react-look#240]
**Version**: 1.0.0 (beta6)  (also seen this on beta5 i think)
**Environment**: React 
**Type**: Bug 

-------------------
#### Description
When I call StyleSheet.create(myStyleObject) twice with the same object, I don't get the same classnames. Furthermore the new classnames are not added to DOM.

#### Steps to reproduce

Execute this code in [tonicdev.com](https://tonicdev.com/56b509234d7b560d00b293e6/56dc2cab0ba4470d0091df85). The link should include the code.

```js
var react = require('react')
var reactDom = require('react-dom')
var StyleSheet = require("react-look").StyleSheet

var styleSheet = {bla: {color: 'red'}}
var stylesA = StyleSheet.create(styleSheet)
var stylesB = StyleSheet.create(styleSheet)

console.log(stylesA.bla)
console.log(stylesB.bla)
```

#### Expected Behavior

I expected the two classes to be the same since it is the same object with the same content.
```javascript
stylesA.bla === stylesB.bla 
```

#### Actual Behavior
```javascript
stylesA.bla !== stylesB.bla
```

**Comment by rofrischmann** [comment]
This actually is not a bug, but a feature by design I guess.
The API was designed to be only called once actually, so recalling the same styles should be considered bad-practice anyways. But sometimes you actually come up with styles that contain the exact same static styles. 
You may now wonder why this (and yes, it kind of makes sense) doesn't return the same classNames at all, but some basic incremented counter as className. Now let my try to explain why this would break dynamic styles in some special cases:
```javascript

// First of all, lets assume we got those two basic Components
const ComponentA = () => <div className={stylesA.box}>text</div>
const ComponentB = () => <span className={stylesB.box}>text</div>

// Using these styles
const stylesA = StyleSheet.create({
   box: {
      color: 'red'
   }
})

const stylesB = StyleSheet.create({
   box: {
      color: 'red',
      'isActive=true': {
         color: 'blue'
      }
   }
})
```
Right, both styles `stylesB.box` and `stylesA.box` will reference a CSS class with just `{color: red}`. So why not return the same className right? The problem is, the classNames gets used to also reference the dynamic styles.
While `stylesA.box` does not contain dynamic styles at all, `stylesB.box` does. If you'd use the same className you could not differentiate which one actually should be used.
In that case e.g. `ReactDOM.render(<ComponentA isActive />, document.body)` would not render a red text, but a blue one, even if stylesA does not implement this.

In addition, `StyleSheet.create` will directly manipulate the styles passed in to avoid an extra assigning step. This could actually be discussed, as a pure predictable version without side-effects could actually prevent problems like this (not getting added to the DOM).
If you still need to do this, please `Object.assing({}, styles)` your styles first.

**Comment by dustin-H** [comment]
Ok, thanks!
