### ISSUE TITLE
Hover nesting

### ISSUE THREAD

**Issue by akshathaP** [rofrischmann/react-look#251]
How to do hover nesting, like the below

test : {
    ':hover':{
      ':before':{
        visibility   : 'visible',
        opacity      : 1,
      },
      ':after':{
        visibility   : 'visible',
        opacity      : 1,
      }
    },
}

**Comment by rofrischmann** [comment]
Could you please just use the issue template which is provided automatically while creating a new issue? I got no idea what you want to achieve, what you expect, what the problem is (what you actually get).
Also please use code highlighting and formatted code. 
As of now I do not see any problem which what you've posted above.

**Comment by akshathaP** [comment]
Thank you, Its fixed
