### ISSUE TITLE
Conditional styles fail for wrapping component

### ISSUE THREAD

**Issue by RylanH** [rofrischmann/react-look#286]
**Version**: 1.0.0 (beta9)
**Environment**: React 
**Type**: Bug

-------------------
#### Description
Conditional styles do not get applied to child elements when they are created by a look component that wraps another look component and passes in the children.

#### Steps to reproduce
```
// InfoButton.js
const styles = StyleSheet.create({
  child: {
    "color=red": {
      // styles that don't get applied
      color: 'red',
    }
  }
});
@look
export default class InfoButton {
...
  render() {
    return (<Button>
      <span className={styles.child} >Hello</span>
    </Button>);
  }
}

// Button.js

const styles = StyleSheet.create({
  root: {
    color: 'black',
  }
});

@look
export default class Button {
...
  render() {
    return (<button className={styles.root}>
      {this.props.children}
    </button>);
  }
}
```

#### Expected Behavior
An `<InfoButton color="red" />` should have the text be red not black.

#### Actual Behavior
Its black.

#### Proposal
Remove this from `react-look > core > resolver.js`
```
function resolveStyles...
...
      // early return if element itself is a Look component
      // it will be resolved anyways
      // if (isLookEnhanced(element)) {
      //   return {
      //     v: element
      //   };
      // }
```
Instead after resolving an element, mark it as resolved and avoid re-resolving an element.

**Comment by rofrischmann** [comment]
Hey @RylanH, Thanks for the detailed issue. You might also want to check out https://github.com/rofrischmann/react-look/issues/253 which discusses the same problem I guess. There you'll also find an answer why this happens and why it can not be fixed right out of the box. 

Your proposal seems legit at first, but fails for other cases. You could either remove the isLookEnhanced at all and iterate all elements over and over (in order to get the props correctly applied). But without the isLookEnhanced you could not just mark it as resolved or you'll see wrong props on your elements again as they get resolved with the props of the root Component that gets rerendered. 

I will close this as it has been discussed earlier without a fitting solution.
