### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by jordanh** [rofrischmann/react-look#291]
#### Proposal

Recently @mattkrick and I were hunting down a bug between [our codebase](https://github.com/ParabolInc/action) and `react-look`. `react-look`'s repository directory structure made this more clunky than it should have been for a couple of reasons:

1. We couldn't use `npm link` and instead had to symlink in `react-look` and `react-look-core` into our project manually

2. More importantly, once we committed our fix to our fork, we were unable to use npm at a specific commit within our private repository. For example, linking to https://github.com/jordanh/react-look/tree/develop/packages/react-look is a no no.

I'd like to propose breaking `react-look` into fours separate modules:

* `react-look`
* `react-look-core`
* `react-look-test-utils`
* and `react-look-native`.

Certainly a sign of project maturity!

Of course, open to any comments to the contrary as well. Perhaps there are advantages of keeping these together I do not see...

**Comment by rofrischmann** [comment]
So you'd like to have 4 different repositories or am I getting that wrong?

**Comment by mattkrick** [comment]
Yep, so `react-look` would depend on `react-look-core`, similar to how `webpack` has a bunch of external dependencies that are only used by webpack itself (https://github.com/webpack/webpack/blob/master/package.json). Or alternatively how `socketCluster` has a core repo that depends on a `server` and `client` repo. https://github.com/socketcluster/socketcluster/.

In addition to being symlink/github-package friendly, it'd also be more inviting to PRs since we could call `npm run test` from the root and only run the necessary tests. In the early days, I could definitely see where the monolithic structure makes sense (a PR requires a change to both `react-look` and `react-look-core`), but now that it's on the cusp of 1.0.0, I'd say it's stable enough to draw that line between modules.

**Comment by rofrischmann** [comment]
Hmm yeah, I think it does not matter how it is structured as long as we have multiple modules, which right now is the case, but I actually did not do the structure well as I did not know how to do it at all.

I'd do it much better by now, but still keep the single repository pattern. Actually if there's a change/bug/request it often needs changes to more than one package, so we'd need to have issues for every repository which is not nice I guess.
But ofc you might convince me why it'd be better at all. I am right now really busy with studies and other projects, so feel free to improve it :P Actually I am working on "new" package for styling with takes advantage of all experience I gained with Look, but is more universal, less complicated and much smaller. It might replace Look at the long term, but that ofc does not mean I will ignore Look nor stop improving it :P I just might need some extern help

**Comment by mattkrick** [comment]
What's your vision for a more modular single repo? I'm definitely no expert on repo management, so it'd be great to learn from.
Also, I'd be interested in checking out your new package! What's it sacrifice to get the size down?

**Comment by rofrischmann** [comment]
Basically how I did it with the new package. Everything is inside a single modules folder, the main package (e.g. react-look-core) provides everything via npm and subpackages only require e.g. `react-look-core/lib/dom` and export it. Then you have different packages only including what they actually need, but yet can do unified testing and have a great overview of all files.

And of course feel free to check it out. It's called Fela (https://github.com/rofrischmann/fela). I am not sure if there is any sacrifice, but its yet not ready for production (but should be soon). It only has 2kb because is does not require React nor wrap any third-party rendering cycle. It just works stand-alone and is dynamic by default. Also the React bindings are kind of "simple", but should be enough to do everything. We also like to chat about it at Gitter (link in the repo). 

First I was trying to use Fela as Look's new "core", but it turned out that it actually would be harder to get everything done with Fela but to keep Look's APIs compared to just create React bindings for Fela itself.

**Comment by jordanh** [comment]
@rofrischmann: first of all _love_ the look of [Fela](https://github.com/rofrischmann/fela) (Any intentional reference to [Fela Kuti](https://en.wikipedia.org/wiki/Fela_Kuti)?). It looks like the in-line style library of my dreams. I particularly like how now I'm in charge of the renderer singleton!

Back to repository layout for `react-look`. Here's the friction:

Let's say we've got some production code based on `react-look` and we find a bug in one of the modules. We're good OSS citizens so we fix it and submit a PR. Meanwhile, we can't wait for the module to be integrated, so we deploy our `package.json` like so:

```js
"react-look": "github:jordanh/react-look#bugfix-tag"
```

With the current directory structure, we're unable to do that. First, we might say, "we'll shoot, just reference the subdirectory." So we try changing our `package.json` to:

```js
"react-look": "github:jordanh/react-look/packages/react-look#bugfix-tag"
```

...but this will also fail as npm disallows reference sub-paths of github repositories.

It'd be nice not to repeat this in Fela. To manage the chaos of versioning and publishing together, it could be a good case to use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

You could use the following structure:

```
+ fela-bundle (docs, & build tools)
   |
   + docs
   + examples
   + scripts
   + packages
      Submodules:
      |
      - fela-core (replacing "modules", npm link'ed from the others for development)
      - fela-beautifier
      - fela-logger
      - fela-perf
      - ...
      - fela
   + ...
``` 

It seems like a hassle, but then we get `npm link` and `npm install github:user/fork`. Otherwise, we've got to continue working around the monolithic directory structure...

Know in either case we'll be happy and supportive users and are very grateful for all your work!

**Comment by jordanh** [comment]
(p.s. I'll be in Leipzig for the summer if you want an in-person jam session!)

**Comment by rofrischmann** [comment]
I believe within Fela we do not need to use submodules as you can always just bump a patch version and auto update the other packages too. This works as all the code is provided by a single npm module though.
I'd love to use the same strategy at Look, but I am really not having the time. Actually I might need someone to maintain Look or to somehow get the ppl to move to Fela if possible. 

And thanks for your kind words about Fela :) and it has nothing to do with Fela Kuti, but with a fictive character from a novel, I will add some infos about the name to the repo soon :P 

PS: Feel free to ping me when you're there! Leipzig is quite some hours away, but maybe I'll be there somehow sometime :P

**Comment by jordanh** [comment]
Hi from Leipzig!

Fair enough. It's a design choice, and one we can certainly live with.

When we've encountered a bug in `react-look` and made local modifications we've been building our own binaries and adding them to our `package.json` like this:

```javascript
  /* ... */
  "react-look": "file:./.mod_bin/react-look-1.0.0-beta9.tgz",
  /* ... */
```

We can close this issue.
